### ISSUE TITLE
Attempt to invoke virtual method 'boolean fr.greweb.rnwebgl.RNWebGLTexture.listenAttached(java.lang.Runnable)' on a null object reference

### ISSUE THREAD

**Issue by vliedel** [react-community/react-native-webgl#66]
Hi, i got this the following error on version 3.15.0:

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.greweb.rnwebgl.RNWebGLTexture.listenAttached(java.lang.Runnable)' on a null object reference
        at fr.greweb.rnwebgl.RNWebGLTextureLoader$2.call(RNWebGLTextureLoader.java:67)
        at fr.greweb.rnwebgl.RNWebGLTextureLoader$1.call(RNWebGLTextureLoader.java:57)
        at fr.greweb.rnwebgl.RNWebGLTextureImageLoader$1.onFailureImpl(RNWebGLTextureImageLoader.java:71)
        at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:59)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by vliedel** [comment]
Found out what caused this error: I called loadTexture() with image: `uri: '/storage/emulated/...jpg` instead of `uri: 'file:///storage/emulated/...jpg`.
Maybe the error message could be a bit more helpful than this?

**Comment by bcgilliom** [comment]
I'm getting this error on a Nexus 5, android 6.0.1, rn-webgl v0.8.0 when I try to load a texture via `const myImage = require('./path./to/myImage.png');`

This seems to work fine on a 5x with android 8

here's the stack trace:
```
03-30 23:39:25.989 21366-21454/com.fractical.cemenemba D/SoLoader: About to load: librnwebgl.so
    librnwebgl.so not found on /data/data/com.fractical.cemenemba/lib-main
03-30 23:39:25.990 21366-21454/com.fractical.cemenemba D/SoLoader: librnwebgl.so found on /data/app/com.fractical.cemenemba-2/lib/arm
    Not resolving dependencies for librnwebgl.so
03-30 23:39:26.026 21366-21454/com.fractical.cemenemba D/SoLoader: Loaded: librnwebgl.so
03-30 23:39:26.528 21366-21828/com.fractical.cemenemba E/AndroidRuntime: FATAL EXCEPTION: FrescoDecodeExecutor-4
    Process: com.fractical.cemenemba, PID: 21366
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.greweb.rnwebgl.RNWebGLTexture.listenAttached(java.lang.Runnable)' on a null object reference
        at fr.greweb.rnwebgl.RNWebGLTextureLoader$2.call(RNWebGLTextureLoader.java:67)
        at fr.greweb.rnwebgl.RNWebGLTextureLoader$1.call(RNWebGLTextureLoader.java:57)
        at fr.greweb.rnwebgl.RNWebGLTextureImageLoader$1.onFailureImpl(RNWebGLTextureImageLoader.java:71)
        at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:57)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:818)
```

Any thoughts?
